export const ListOrchids = [
  {
    Id: "1",
    name: "Bulbophyllum",
    rating: 3.5,
    isSpecial: true,
    image: "https://i.pinimg.com/564x/82/bd/6c/82bd6c1ab2f9a87e15bbd6ca5de28d43.jpg",
    color: "pink",
    origin: "Southeast Asia",
    category: "Bulbophyllum",
    description: "Known for its unusual flowers, Bulbophyllum orchids thrive in warm, humid environments. They are often found in tropical regions and are notable for their unique shapes and sizes.",
  },
  {
    Id: "2",
    name: "Phalaenopsis",
    rating: 4,
    isSpecial: false,
    image: "https://i.pinimg.com/564x/22/b0/30/22b030d59e9350071ca024a1183f0999.jpg",
    color: "white",
    origin: "Philippines",
    category: "Phalaenopsis",
    description: "One of the most popular orchids, Phalaenopsis, or 'moth orchids,' are known for their ease of care and long-lasting blooms, making them ideal for beginners.",
  },
  {
    Id: "3",
    name: "Dendrobium",
    rating: 4,
    isSpecial: false,
    image: "https://i.pinimg.com/564x/ff/54/a1/ff54a170b21da27ad7ae6b47f70f76be.jpg",
    color: "purple",
    origin: "Australia",
    category: "Dendrobium",
    description: "Dendrobium orchids are versatile and come in many varieties, ranging from large sprays of flowers to compact and delicate blooms.",
  },
  {
    Id: "4",
    name: "Cattleya",
    rating: 5,
    isSpecial: true,
    image: "https://i.pinimg.com/736x/34/cb/0f/34cb0f45824619c2b0ef66337a705193.jpg",
    color: "white",
    origin: "Brazil",
    category: "Cattleya",
    description: "Known as the 'Queen of Orchids,' Cattleyas are renowned for their spectacular and fragrant flowers, often used in corsages and floral arrangements.",
  },
  {
    Id: "5",
    name: "Oncidium",
    rating: 3,
    isSpecial: false,
    image: "https://i.pinimg.com/564x/98/bb/64/98bb643cb0a93d39521c1b940bb53e1e.jpg",
    color: "gold",
    origin: "Colombia",
    category: "Oncidium",
    description: "Oncidiums are commonly called 'dancing lady' orchids due to their distinct, bright, and fluttery petals. They thrive in warm climates and need lots of light.",
  },
  {
    Id: "6",
    name: "Vanda",
    rating: 5,
    isSpecial: true,
    image: "https://i.pinimg.com/564x/06/8e/57/068e57866178d21de2bceb0016b90034.jpg",
    color: "white",
    origin: "Thailand",
    category: "Vanda",
    description: "Vanda orchids are admired for their striking colors and large blooms. They are commonly used as show plants and are known for their unique aerial root systems.",
  },
  {
    Id: "7",
    name: "Cymbidium",
    rating: 4,
    isSpecial: true,
    image: "https://i.pinimg.com/564x/73/20/0f/73200f3bf52dac2576354f1d3b3c7cdc.jpg",
    color: "pink",
    origin: "China",
    category: "Cymbidium",
    description: "Cymbidium orchids are prized for their long-lasting flowers and are often used in floral arrangements. They prefer cooler temperatures compared to other orchids.",
  },
  {
    Id: "8",
    name: "Miltonia",
    rating: 3,
    isSpecial: false,
    image: "https://i.pinimg.com/564x/91/dd/8f/91dd8f072cbf4afec9b989c751ee5c47.jpg",
    color: "white",
    origin: "Brazil",
    category: "Miltonia",
    description: "Miltonia orchids, often called 'pansy orchids,' have large, flat flowers that resemble pansies. They are known for their vivid colors and patterns.",
  },
  {
    Id: "9",
    name: "Zygopetalum",
    rating: 4,
    isSpecial: false,
    image: "https://i.pinimg.com/564x/32/91/d7/3291d7da1728293a650b42ec2803eef5.jpg",
    color: "pink",
    origin: "Brazil",
    category: "Zygopetalum",
    description: "Zygopetalum orchids are appreciated for their exotic, fragrant flowers, which often have striking color patterns. They are known to grow well in intermediate temperatures.",
  },
  {
    Id: "10",
    name: "Paphiopedilum",
    rating: 5,
    isSpecial: true,
    image: "https://i.pinimg.com/564x/af/9f/69/af9f6963333b21da2788b7f306981502.jpg",
    color: "white",
    origin: "Asia",
    category: "Paphiopedilum",
    description: "Also known as 'slipper orchids,' Paphiopedilum orchids are known for their distinctive pouch-like flowers. They grow well in cooler environments.",
  },
  {
    Id: "11",
    name: "Brassia",
    rating: 4,
    isSpecial: true,
    image: "https://i.pinimg.com/564x/fd/e5/f1/fde5f10731c108ddce22a320b40c31ca.jpg",
    color: "white",
    origin: "Central America",
    category: "Brassia",
    description: "Brassia orchids are known as 'spider orchids' due to their long, thin petals. They thrive in warm, humid environments and often emit a spicy fragrance.",
  },
  {
    Id: "12",
    name: "Coelogyne",
    rating: 3,
    isSpecial: false,
    image: "https://i.pinimg.com/564x/51/a5/d4/51a5d4bfd3abb8a1844687e3580e1e08.jpg",
    color: "white",
    origin: "Asia",
    category: "Coelogyne",
    description: "Coelogyne orchids are known for their gracefully arching sprays of flowers. They grow in cool to intermediate conditions and are commonly found in the Himalayas.",
  },
  {
    Id: "13",
    name: "Lycaste",
    rating: 4,
    isSpecial: false,
    image: "https://i.pinimg.com/564x/14/62/84/1462844f864ee2aca0f3d3c09321fba8.jpg",
    color: "red",
    origin: "Central America",
    category: "Lycaste",
    description: "Lycaste orchids have large, fragrant flowers and are known for their striking appearance. They are relatively easy to grow in temperate climates.",
  },
  {
    Id: "14",
    name: "Catasetum",
    rating: 5,
    isSpecial: false,
    image: "https://i.pinimg.com/564x/b2/fe/c9/b2fec9c15bb0ae1e13ea83f3f28882c3.jpg",
    color: "orange",
    origin: "South America",
    category: "Catasetum",
    description: "Catasetum orchids are known for their unique sexual dimorphism, producing male and female flowers on separate plants. They grow best in warm, humid environments.",
  },
  {
    Id: "15",
    name: "Angraecum",
    rating: 4,
    isSpecial: true,
    image: "https://i.pinimg.com/564x/4e/bf/88/4ebf88f2f52e976e21b9ac4103965753.jpg",
    color: "white",
    origin: "Madagascar",
    category: "Angraecum",
    description: "Angraecum orchids are best known for their star-shaped flowers and often bloom at night. They prefer warm, humid climates and are typically fragrant.",
  },
  {
    Id: "16",
    name: "Dendrobium nobile",
    rating: 5,
    isSpecial: true,
    image: "https://i.pinimg.com/564x/d0/63/1a/d0631a7c5e3c98b22144061d91c1964a.jpg",
    color: "white",
    origin: "China",
    category: "Dendrobium",
    description: "Dendrobium nobile is a popular variety known for its abundant and vibrant flowers. It prefers cooler temperatures and bright light for optimal growth.",
  },
];
